### PR TITLE
Optimize group by query in Suministros list view

### LINKED ISSUE #84: Optimize Suministro “group by”
The way `suministró` records are fetched could be problematic as the amount of records grow. The `group by` could be done at a DB query level reducing operations and memory usage. 

https://github.com/Code4PuertoRico/suministrospr/blob/a0f6a70cc2f8894dd79a41a43e67f35d851e51ea/suministrospr/suministros/views.py#L26

@gcollazo This is not a blocker for v1 just something to keep an eye out for.

### PR DESCRIPTION
**Pull request by rnegron**
Took the approach of splitting `Municipality` into its own model for a cleaner query... I think having a separate model would also be useful for future features coming up which may want to have a `Municipality` foreign key. Thoughts?

I made a data migration in migration `0007_auto_20200116_0218.py` to automatically create all Municipalities before first boot.

**Edit** I see the Django version already launched, so this PR needs to consider migrating data or a different approach.

Closes #84.

### CODE REVIEW

**Comment by rnegron** [comment]
@jpadilla Do you think it's worth it to do the required 4-step migration in order to get the foreign key working in the same field as before, or would you prefer a different approach to this?

**Comment by rnegron** [comment]
Still testing...

```
Migration 6: Creates the `Municipality` table and adds a `taggit` field to the `Suministro` model
Migration 7: Adds verbose names to `Suministro` model and adds the `title` index
Migraiton 8: Data migration for all the municipalities
Migration 9: Adds a new field `municipios_fk` to the `Suministro` model
Migration 10: Data migration to copy data from the `municipios` field to the new `municipios_fk` field
Migration 11: Removes the old `municipios` field
Migration 12: Renames the `municipios_fk` field to `municipios`
```

**Comment by rnegron** [comment]
I did the following test and confirmed all was working OK:

1. Delete local DB
2. Checkout current `master` branch
3. Run migrations available in `master` branch
4. Run data import from the previous site
5. Switch to this branch
6. Run new migrations
7. Go into DB and see expected columns
8. Open development server and click around a lot

**Comment by arielo** [comment]
@rnegron Looks good to me. The only thing is that if you remove these migrations from this PR and have them skip the a release, you can avoid downtime on the next deploy. Since these migrations are removing fields used by the current release.

suministrospr/suministros/migrations/0011_remove_suministro_municipality.py
suministrospr/suministros/migrations/0012_auto_20200116_1937.py

**Comment by rnegron** [comment]
@arielo Those last two migrations don't really have an effect on the downtime of the deployment since they are mostly cleanup. The downtime would primarily come from locking the database to perform the migrations. The codebase itself is now expecting a foreign key in the `municipios`field, which means the last migration is required for the code to run.

**Comment by arielo** [comment]
@rnegron I meant downtime on the previous release caused by those fields being missing in the schema just as the new migration runs and right before the new release boots. Might just be a dismissable blip. Maybe @jpadilla has some thoughts here?

**Comment by jpadilla** [comment]
> @rnegron I meant downtime on the previous release caused by those fields being missing in the schema just as the new migration runs and right before the new release boots. Might just be a dismissable blip. Maybe @jpadilla has some thoughts here?

@arielo yeah, not that much data for it to be too much of a risk. Current cached response will be untouched, only creating/updating at the time migrations are in progress _might_ fail.

@rnegron gracias!

**Comment by rnegron** [comment]
@jpadilla A ti 😄

**Review by jpadilla — APPROVED** [review]

**Pull request merged**
